extends: airbnb
rules:
  no-underscore-dangle: 0
  semi: ["error", "never"]
  arrow-parens: ["error", "as-needed"]
  max-len: ["error", { "code": 120, "ignoreTrailingComments": true, "ignoreUrls": true, "ignoreStrings": true, "ignoreComments": true }]
  no-console: ["error", { allow: ["warn", "error", "group", "groupEnd"] }]
  react/jsx-filename-extension: 0
  import/no-cycle: 0
  react/sort-comp: 0
  react/forbid-prop-types: 0
  react/destructuring-assignment: 0
  react/jsx-one-expression-per-line: 0
  import/no-extraneous-dependencies: 0
env:
  node: true
  browser: true
  es6: true
  jest: true
parser: babel-eslint
parserOptions:
  sourceType: 'module'
  ecmaFeatures:
    jsx: true
    modules: true
    destructuring: true
    classes: true
    forOf: true
    blockBindings: true
    arrowFunctions: true
plugins:
- react
