extends: airbnb
rules:
  semi: ["error", "never"]
  max-len: ["error", { "code": 120, "ignoreTrailingComments": true, "ignoreUrls": true, "ignoreStrings": true, "ignoreComments": true }]
  react/jsx-filename-extension: 0
  import/no-extraneous-dependencies: 0 # Incorrect work with decorators
  jsx-a11y/anchor-is-valid: ["error", {"components": [], "specialLink": ["hrefLeft", "hrefRight"], "aspects": ["noHref", "invalidHref", "preferButton"]}]
  jsx-a11y/href-no-hash: 0
  react/forbid-prop-types: 0
env:
  node: true
  browser: true
  es6: true
  jest: true
parser: babel-eslint
parserOptions:
  sourceType: 'module'
  ecmaFeatures:
    jsx: true
    modules: true
    destructuring: true
    classes: true
    forOf: true
    blockBindings: true
    arrowFunctions: true
    experimentalObjectRestSpread: true
plugins:
- react
