include:
  - 'template_ci/job_best_practices.yml'
  - 'template_ci/job_build.yml'
  - 'template_ci/job_deploy.yml'
  - 'template_ci/job_publish.yml'

image: docker:latest
before_script:
  - apk add --no-cache git
services:
  - docker:dind

stages:
  - build
  - best_practices
  - publish
  - deploy

variables:
  RELEASE_NAME: react-app
  HELM_PATH: ops/Helm/react-app
  DOCKER_IMAGE_URL: cros/react-app

build:staging:
  <<: *job_build
  retry: 2
  script:
    - docker build -t $CI_REGISTRY_IMAGE --build-arg REACT_APP_API_URL=$REACT_APP_API_URL --build-arg REACT_APP_GOOGLE_RECAPTCHA_SITEKEY=$REACT_APP_GOOGLE_RECAPTCHA_SITEKEY .
    - docker push $CI_REGISTRY_IMAGE
    # - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG --build-arg REACT_APP_API_URL=$REACT_APP_API_URL --build-arg REACT_APP_GOOGLE_RECAPTCHA_SITEKEY=$REACT_APP_GOOGLE_RECAPTCHA_SITEKEY .
    # - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
  only:
    - /^(?:0|[1-9]\d*)\.(?:0|[1-9]\d*)\.(?:0|[1-9]\d*)-rc(?:0|[1-9]\d*)$/

build:production:
  <<: *job_build
  script:
    - docker build -t $CI_REGISTRY_IMAGE --build-arg REACT_APP_API_URL=$REACT_APP_API_URL --build-arg REACT_APP_GOOGLE_RECAPTCHA_SITEKEY=$REACT_APP_GOOGLE_RECAPTCHA_SITEKEY .
    - docker push $CI_REGISTRY_IMAGE

    - docker tag $CI_REGISTRY_IMAGE $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
  only:
    - /^(?:0|[1-9]\d*)\.(?:0|[1-9]\d*)\.(?:0|[1-9]\d*)\.?(?:0|[1-9]\d*)?$/

eslint:
  <<: *job_best_practices
  script:
    - npm run lint

unit-test:
  <<: *job_best_practices
  script:
    - npm test

flow typing:
  <<: *job_best_practices
  script:
    - npm run flow

registry:staging:
  <<: *job_publish
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker pull $CI_REGISTRY_IMAGE
  script:
    - docker login -u $DOCKER_USER -p $DOCKER_PASS
    - docker tag $CI_REGISTRY_IMAGE $DOCKER_IMAGE_URL
    - docker push $DOCKER_IMAGE_URL
  only:
    - /^(?:0|[1-9]\d*)\.(?:0|[1-9]\d*)\.(?:0|[1-9]\d*)-rc(?:0|[1-9]\d*)$/

registry:production:
  <<: *job_publish
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker pull $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
  script:
    - docker login -u $DOCKER_USER -p $DOCKER_PASS

    - docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG $DOCKER_IMAGE_URL
    - docker push $DOCKER_IMAGE_URL

    - docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG $DOCKER_IMAGE_URL:$CI_COMMIT_TAG
    - docker push $DOCKER_IMAGE_URL:$CI_COMMIT_TAG
  only:
    - /^(?:0|[1-9]\d*)\.(?:0|[1-9]\d*)\.(?:0|[1-9]\d*)\.?(?:0|[1-9]\d*)?$/

chart:
  <<: *job_publish
  script:
  # Install tool
    - apk add --update git openssl

  # install Helm
    - wget https://kubernetes-helm.storage.googleapis.com/helm-v2.7.2-linux-amd64.tar.gz
    - tar -xvf helm-v2.7.2-linux-amd64.tar.gz
    - mv linux-amd64/helm /usr/local/bin/helm
    - helm init -c

  # update charts
    - git clone https://$GITHUB_USER:$GITHUB_PASSWORD@github.com/micro-company/charts.git
    - helm package $HELM_PATH
    - mv *.tgz charts/docs
    - helm repo index charts/docs
    - cd charts
    - git add .
    - git config --global user.email "authmicroservice@gmail.com"
    - git config --global user.name "CI bot"
    - git commit -m "Add/Update chart $CI_PROJECT_NAME:$CI_COMMIT_TAG"
    - git push

deploy:staging:
  <<: *job_deploy
  variables:
    HELM_NAMESPACE: minikube
  only:
    - /^(?:0|[1-9]\d*)\.(?:0|[1-9]\d*)\.(?:0|[1-9]\d*)-rc(?:0|[1-9]\d*)$/
